import type { Review } from './types'

export const reviews: Review[] = [
  {
    id: 'rev1',
    authorId: 'ana-c',
    authorName: 'Ana Costa',
    authorAvatar: '/images/avatar-4.png',
    targetId: 'sofia-m',
    rating: 5,
    comment: 'Amazing driver! Very friendly and the car was immaculate. Highly recommend!',
    date: '12 Jun 2024',
    rideRoute: 'Lisbon → Porto',
  },
  {
    id: 'rev2',
    authorId: 'tomas-r',
    authorName: 'Tomás Ribeiro',
    authorAvatar: '/images/avatar-2.png',
    targetId: 'sofia-m',
    rating: 5,
    comment: 'Punctual, comfortable ride. Sofia is a great driver — will book again.',
    date: '05 Jun 2024',
    rideRoute: 'Porto → Lisbon',
  },
  {
    id: 'rev3',
    authorId: 'lucas-f',
    authorName: 'Lucas Ferreira',
    authorAvatar: '/images/avatar-3.png',
    targetId: 'sofia-m',
    rating: 4,
    comment: 'Good ride overall. Left a few minutes late but arrived on time.',
    date: '28 May 2024',
    rideRoute: 'Lisbon → Coimbra',
  },
  {
    id: 'rev4',
    authorId: 'sofia-m',
    authorName: 'Sofia Martins',
    authorAvatar: '/images/avatar-1.png',
    targetId: 'tomas-r',
    rating: 5,
    comment: 'Great passenger, very respectful and on time. Would welcome again.',
    date: '10 Jun 2024',
    rideRoute: 'Lisbon → Porto',
  },
  {
    id: 'rev5',
    authorId: 'miguel-s',
    authorName: 'Miguel Santos',
    authorAvatar: '/images/avatar-5.png',
    targetId: 'lucas-f',
    rating: 5,
    comment: 'Tesla ride was super comfortable. Lucas is professional and friendly.',
    date: '08 Jun 2024',
    rideRoute: 'Lisbon → Porto',
  },
]
