import type { Vehicle } from './types'

export const vehicles: Vehicle[] = [
  {
    id: 'v1',
    make: 'Volkswagen',
    model: 'Golf',
    year: 2021,
    color: 'Silver',
    licensePlate: 'AA-00-BB',
    seats: 4,
    type: 'hatchback',
  },
  {
    id: 'v2',
    make: 'Toyota',
    model: 'Corolla',
    year: 2020,
    color: 'Blue',
    licensePlate: 'CC-11-DD',
    seats: 4,
    type: 'sedan',
  },
  {
    id: 'v3',
    make: 'Tesla',
    model: 'Model 3',
    year: 2022,
    color: 'White',
    licensePlate: 'EE-22-FF',
    seats: 4,
    type: 'electric',
  },
  {
    id: 'v4',
    make: 'Renault',
    model: 'Clio',
    year: 2019,
    color: 'Red',
    licensePlate: 'GG-33-HH',
    seats: 4,
    type: 'hatchback',
  },
  {
    id: 'v5',
    make: 'Peugeot',
    model: '508',
    year: 2021,
    color: 'Grey',
    licensePlate: 'II-44-JJ',
    seats: 4,
    type: 'sedan',
  },
  {
    id: 'v6',
    make: 'Hyundai',
    model: 'Ioniq',
    year: 2023,
    color: 'Green',
    licensePlate: 'KK-55-LL',
    seats: 4,
    type: 'electric',
  },
]
